name: Package program

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  # build:
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: 1.20.x
  #     - name: Install dependencies
  #       run: go get .
  #     - name: Test with Go
  #       run: go test
  #     - name: Build package
  #       run: go build -o mlm.exe
  #     - name: Upload Go package
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: windows-exec
  #         path: mlm.exe
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}